spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tinybite

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    group:
      local: 'local'
      dev: 'dev'
      test: 'test'

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

sms:
  api-key: ${SMS_API_KEY}
  api-secret: ${SMS_API_SECRET}

apple:
  client-id: ${APPLE_CLIENT_ID}

google:
  android-id: ${GOOGLE_ANDROID_CLIENT_ID}
  ios-id: ${GOOGLE_IOS_CLIENT_ID}

naver:
  client-id: ${NAVER_CLIENT_ID}
  secret: ${NAVER_CLIENT_SECRET}

fcm:
  url: https://fcm.googleapis.com/v1/projects/${FCM_PROJECT_ID}/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: ${FCM_PROJECT_ID}

default:
  image:
    thumbnail:
      delivery: ${DEFAULT_IMAGE_DELIVERY}
      grocery: ${DEFAULT_IMAGE_GROCERY}
      household: ${DEFAULT_IMAGE_HOUSEHOLD}
    detail:
      delivery: ${DEFAULT_DETAIL_IMAGE_DELIVERY}
      grocery: ${DEFAULT_DETAIL_IMAGE_GROCERY}
      household: ${DEFAULT_DETAIL_IMAGE_HOUSEHOLD}