services:
  nginx:
    container_name: nginx
    image: nginx:1.27.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/tinybite/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/tinybite/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/tinybite/data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - tinybite-network

  redis:
    container_name: redis
    image: redis:7.2.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - tinybite-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /home/ubuntu/tinybite/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/tinybite/data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    networks:
      - tinybite-network

volumes:
  redis_data:

networks:
  tinybite-network:
    external: true