services:
  tinybite-api-blue:
    image: ghcr.io/tinybite-2025/tinybite-server:latest
    container_name: tinybite-api-blue
    volumes:
      - /home/ubuntu/tinybite/firebase/tinybite_fcm.json:/app/resources/firebase/tinybite_fcm.json:ro
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - tinybite-network

networks:
  tinybite-network:
    external: true